export enum PostShowConstants {
    POSTSHOW = 'POSTSHOW',
    POSTSHOW_SUCCESS = 'POSTSHOW SUCCESS',
    POSTSHOW_FAILURE = 'POSTSHOW FAILURE',
}

export enum FetchCommentsConstants {
    FETCH_COMMENTS = 'FETCH COMMENTS',
    FETCH_COMMENTS_SUCCESS = 'FETCH COMMENTS SUCCESS',
    FETCH_COMMENTS_FAILURE = 'FETCH COMMENTS FAILURE',
}

export enum CommentConstants {
    COMMENT = 'COMMENT',
    COMMENT_SUCCESS = 'COMMENT SUCCESS',
    COMMENT_FAILURE = 'COMMENT FAILURE',
}