export enum PostsPreviewConstants {
    POSTSPREVIEW = 'POSTSPREVIEW',
    POSTSPREVIEW_SUCCESS = 'POSTSPREVIEW SUCCESS',
    POSTSPREVIEW_FAILURE = 'POSTSPREVIEW FAILURE',
}

export enum UpdatePost {
    UPDATE_POST = 'UPDATE POST',
}