export enum PostsPreviewConstants {
    POSTS_PREVIEW = 'POSTS_PREVIEW',
    POSTS_PREVIEW_SUCCESS = 'POSTS_PREVIEW SUCCESS',
    POSTS_PREVIEW_FAILURE = 'POSTS_PREVIEW FAILURE',
}

export enum UpdatePost {
    UPDATE_POST = 'UPDATE POST',
}

export enum FetchFeedsConstants {
    FETCH_FEEDS = 'FETCH_FEEDS',
    FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS SUCCESS',
    FETCH_FEEDS_FAILURE = 'FETCH_FEEDS FAILURE',
}
