export enum PostsPreviewConstants {
    POSTS_PREVIEW = 'POSTS PREVIEW',
    POSTS_PREVIEW_SUCCESS = 'POSTS PREVIEW SUCCESS',
    POSTS_PREVIEW_FAILURE = 'POSTS PREVIEW FAILURE',
}

export enum UpdatePost {
    UPDATE_POST = 'UPDATE POST',
}

export enum FetchFeedsConstants {
    FETCH_FEEDS = 'FETCH FEEDS',
    FETCH_FEEDS_SUCCESS = 'FETCH FEEDS SUCCESS',
    FETCH_FEEDS_FAILURE = 'FETCH FEEDS FAILURE',
}
