export enum SettingsConstants {
    SETTINGS = 'SETTINGS',
    SETTINGS_SUCCESS = 'SETTINGS SUCCESS',
    SETTINGS_FAILURE = 'SETTINGS FAILURE',


    LOGOUT = 'LOGOUT',
    LOGOUT_SUCCESS = 'LOGOUT SUCCESS',
    LOGOUT_FAILURE = 'LOGOUT FAILURE',

    SAVE = 'SAVE',
    SAVE_SUCCESS = 'SAVE SUCCESS',
    SAVE_FAILURE = 'SAVE FAILURE',
}